### ISSUE TITLE
Добавить атрибуты версии для элементов которые были изменены

### ISSUE THREAD

**Issue by bobrovskayaa** [Razzka/babel-plugin-react-element-info-unique#1]
В плагин передаем специальный JSON в виде
```
{
    name: '<version>',
    files: [...]
}
```
где, name - это название версии, а files - это список относительных путей к jsx элементам которые были изменены в этой версии.

плагин должен сопоставить относительные пути пришедшие в JSON с теми которые относятся к ноде, и добавить в этом случае атрибут в который запишется значение из name в JSON

Глобальная цель - дать возможность увидеть какие элементы были изменены между версиями для регрессионного тестирования/

**Comment by pavelpower** [comment]
Неплохо будет потом создать еще одну задачку, в которой будет возможность передачи JOSN через pipe оператор. Если это возможно с бабель плагином.
+ Возможно нужно будет брать из tmp файла.
